name: Build apple-arm64e-upstream-next Toolchain for Apple Silicon Mac

on:
  workflow_dispatch:
  push:
    branches: [apple-arm64e-upstream-next]

jobs:
  build:
    runs-on: macos-14
    env:
      GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
        with:
          ref: "apple-arm64e-upstream-next"
          submodules: "recursive"

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        shell: bash
        run: |
          brew install cmake
          brew install ninja
      
      - name: Build
        shell: bash
        run: |
          mkdir build
          cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES=arm64 -DLLVM_ENABLE_PROJECTS=clang  -DLLVM_TARGETS_TO_BUILD="X86;ARM;AArch64" -DLLVM_ENABLE_ZSTD=OFF -DCMAKE_OSX_DEPLOYMENT_TARGET=12.0 -DLLVM_CREATE_XCODE_TOOLCHAIN=ON  -DLLVM_INCLUDE_TESTS=OFF -DLLVM_INCLUDE_EXAMPLES=OFF -DLLVM_INCLUDE_UTILS=OFF -DLLVM_INCLUDE_BENCHMARKS=OFF -DLLVM_BUILD_TOOLS=OFF -DLLVM_INSTALL_TOOLCHAIN_ONLY=ON -DCMAKE_INSTALL_PREFIX="./install" ../llvm
          ninja
          ninja install-xcode-toolchain
          tar -czvf Hikari_LLVM19.0.0git_Apple-Silicon-Mac.tar.gz ./install/Toolchains/Hikari_LLVM19.0.0git.xctoolchain
  
      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: Hikari_LLVM19.0.0git_Apple-Silicon-Mac.tar.gz
          path: build/Hikari_LLVM19.0.0git_Apple-Silicon-Mac.tar.gz
