name: Update Submodules

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  update_submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout llvm-swift-5.7.2-RELEASE
        uses: actions/checkout@v4.1.6
        with:
          ref: "llvm-swift-5.7.2-RELEASE"
          submodules: "recursive"

      - name: Set Git config
        run: |
          git config user.name 'Submodule AutoUpdater'
          git config user.email 'actions@users.noreply.github.com'

      - name: Update submodule llvm-swift-5.7.2-RELEASE
        id: swift572
        run: |
          git submodule update --remote
          if [ -n "$(git status --porcelain)" ]; then
            echo "Some files have been modified"
            echo "HAS_CHANGES=1" >> $GITHUB_OUTPUT
            git add .
            git commit -m "update submodule"
          fi

      - name: Push changes llvm-swift-5.7.2-RELEASE
        if: ${{ steps.swift572.outputs.HAS_CHANGES == '1' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: llvm-swift-5.7.2-RELEASE

      - name: Checkout llvm-swift-5.8-RELEASE
        uses: actions/checkout@v4.1.6
        with:
          ref: "llvm-swift-5.8-RELEASE"
          submodules: "recursive"

      - name: Update submodule llvm-swift-5.8-RELEASE
        id: swift58
        run: |
          git submodule update --remote
          if [ -n "$(git status --porcelain)" ]; then
            echo "Some files have been modified"
            echo "HAS_CHANGES=1" >> $GITHUB_OUTPUT
            git add .
            git commit -m "update submodule"
          fi

      - name: Push changes llvm-swift-5.8-RELEASE
        if: ${{ steps.swift58.outputs.HAS_CHANGES == '1' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: llvm-swift-5.8-RELEASE

      - name: Checkout llvm-swift-5.9-RELEASE
        uses: actions/checkout@v4.1.6
        with:
          ref: "llvm-swift-5.9-RELEASE"
          submodules: "recursive"

      - name: Update submodule llvm-swift-5.9-RELEASE
        id: swift59
        run: |
          git submodule update --remote
          if [ -n "$(git status --porcelain)" ]; then
            echo "Some files have been modified"
            echo "HAS_CHANGES=1" >> $GITHUB_OUTPUT
            git add .
            git commit -m "update submodule"
          fi

      - name: Push changes llvm-swift-5.9-RELEASE
        if: ${{ steps.swift59.outputs.HAS_CHANGES == '1' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: llvm-swift-5.9-RELEASE

      - name: Checkout llvm-swift-5.10-RELEASE
        uses: actions/checkout@v4.1.6
        with:
          ref: "llvm-swift-5.10-RELEASE"
          submodules: "recursive"

      - name: Update submodule llvm-swift-5.10-RELEASE
        id: swift510
        run: |
          git submodule update --remote
          if [ -n "$(git status --porcelain)" ]; then
            echo "Some files have been modified"
            echo "HAS_CHANGES=1" >> $GITHUB_OUTPUT
            git add .
            git commit -m "update submodule"
          fi

      - name: Push changes llvm-swift-5.10-RELEASE
        if: ${{ steps.swift510.outputs.HAS_CHANGES == '1' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: llvm-swift-5.10-RELEASE

      - name: Checkout apple-arm64e-upstream-next
        uses: actions/checkout@v4.1.6
        with:
          ref: "apple-arm64e-upstream-next"
          submodules: "recursive"
  
      - name: Update submodule apple-arm64e-upstream-next
        id: apple-arm64e
        run: |
          git submodule update --remote
          if [ -n "$(git status --porcelain)" ]; then
            echo "Some files have been modified"
            echo "HAS_CHANGES=1" >> $GITHUB_OUTPUT
            git add .
            git commit -m "update submodule"
          fi
  
      - name: Push changes apple-arm64e-upstream-next
        if: ${{ steps.apple-arm64e.outputs.HAS_CHANGES == '1' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: apple-arm64e-upstream-next
  

      - name: Checkout llvm-15.0.2rel
        uses: actions/checkout@v4.1.6
        with:
          ref: "llvm-15.0.2rel"
          submodules: "recursive"

      - name: Update submodule llvm-15.0.2rel
        id: llvm1502
        run: |
          git submodule update --remote
          if [ -n "$(git status --porcelain)" ]; then
            echo "Some files have been modified"
            echo "HAS_CHANGES=1" >> $GITHUB_OUTPUT
            git add .
            git commit -m "update submodule"
          fi

      - name: Push changes llvm-15.0.2rel
        if: ${{ steps.llvm1502.outputs.HAS_CHANGES == '1' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: llvm-15.0.2rel

      - name: Checkout llvm-16.0.0rel
        uses: actions/checkout@v4.1.6
        with:
          ref: "llvm-16.0.0rel"
          submodules: "recursive"

      - name: Update submodule llvm-16.0.0rel
        id: llvm1600
        run: |
          git submodule update --remote
          if [ -n "$(git status --porcelain)" ]; then
            echo "Some files have been modified"
            echo "HAS_CHANGES=1" >> $GITHUB_OUTPUT
            git add .
            git commit -m "update submodule"
          fi

      - name: Push changes llvm-16.0.0rel
        if: ${{ steps.llvm1600.outputs.HAS_CHANGES == '1' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: llvm-16.0.0rel

      - name: Checkout llvm-17.0.6rel
        uses: actions/checkout@v4.1.6
        with:
          ref: "llvm-17.0.6rel"
          submodules: "recursive"

      - name: Update submodule llvm-17.0.6rel
        id: llvm1706
        run: |
          git submodule update --remote
          if [ -n "$(git status --porcelain)" ]; then
            echo "Some files have been modified"
            echo "HAS_CHANGES=1" >> $GITHUB_OUTPUT
            git add .
            git commit -m "update submodule"
          fi

      - name: Push changes llvm-17.0.6rel
        if: ${{ steps.llvm1706.outputs.HAS_CHANGES == '1' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: llvm-17.0.6rel

      - name: Checkout llvm-18.1.8rel
        uses: actions/checkout@v4.1.6
        with:
          ref: "llvm-18.1.8rel"
          submodules: "recursive"
  
      - name: Update submodule llvm-18.1.8rel
        id: llvm1818
        run: |
          git submodule update --remote
          if [ -n "$(git status --porcelain)" ]; then
            echo "Some files have been modified"
            echo "HAS_CHANGES=1" >> $GITHUB_OUTPUT
            git add .
            git commit -m "update submodule"
          fi
  
      - name: Push changes llvm-18.1.8rel
        if: ${{ steps.llvm1818.outputs.HAS_CHANGES == '1' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: llvm-18.1.8rel
