name: Update submodule

on:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  updateSubmodule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Update submodule
        run: |
          if git submodule update --remote; then
            git config user.name 'Submodule AutoUpdater'
            git config user.email 'actions@users.noreply.github.com'
            git add .
            git commit -m "update submodule"
            git push
          fi
